cablehead/python-consul

consul/base.py
tests/test_std.py

Again, not a massive amount to test here without a proper cluster. Name gets suffixed with the datacenter name, so test that is observed.

Closes #13. Added flag to query wan members

---

consul/base.py
tests/test_std.py

I think this does the trick. I copied your tests for the service endpoint and fixed them up a bit. It's not exhaustive (I only check `any` and `passing`, for example), but I hope  it's a good enough first step.

Closes #24. Adding support for the /health/state/* endpoint

---

consul/base.py

Any kv.get 500 response raises ValueError attempting to json decode the non-json response.
Raise ConsulException on response code 500.

Raise ConsulException on kv GET 500 response code.

---

setup.py

It's impossible to use `consul.aio` if installing via `pip3 install python-consul`, as the module is missing in tarball uploaded to pypi. I guess it's because pypi upload is done using python2 and `asyncio` is removed from distribution in this case. The pull request tries to fix it by moving `asyncio` checking to install phase only.

there's no consul.aio in python-consul package in pypi

---

requirements.txt

```
$ pip install 'six==1.3'
.. cut ...
$ python -c 'import consul'
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "consul/__init__.py", line 3, in <module>
from consul.std import Consul
File "consul/std.py", line 1, in <module>
from six.moves import urllib
ImportError: cannot import name urllib
```
Works with 1.4 up.

require six>=1.4 (python_consul won't work with earlier versions)

---

consul/base.py

I tried supplying a numerical value for the wait parameter, but that resulted in an exception. I then found that one of your tests sets the wait parameter to '10ms' so I thought it would be useful to give that example up front in the docs.

Clarify docs to give an example value for Consul.kv.get's wait parameter

---

consul/aio.py
tests/test_aio.py

Add new method ``close`` to ``consul.aio.Consul``, to finalize all existing http connections in ``aiohttp.TCPConnector``. Should fix #47
Please review.

add close method to aio.Counsul to finalize http connections

---

consul/base.py

Support creation of ALCs with explicit ID.
Documentation: https://www.consul.io/docs/agent/http/acl.html
```
The ID field may be provided, and if omitted a random UUID will be
generated. The security of the ACL system depends on the difficulty of
guessing the token. Tokens should not be generated in a predictable
manner or with too little entropy.
```

Allow ALC creation with explicit ID.

---

consul/std.py

By using a persistent requests.session, requests can use [Keep-Alives](http://docs.python-requests.org/en/latest/user/advanced/#keep-alive), resulting in better performance, when the client is doing repeated requests to Consul.
When testing the [ansible consul_io inventory script](https://github.com/ansible/ansible/blob/devel/contrib/inventory/consul_io.py), it takes ~12 seconds (because it does 774 HTTP requests!) to hit all nodes without this, and about ~8 seconds with this, which is a pretty decent speedup.
Cc: @sgargan, @sudarkoff, @aconrad

Use requests.session for performance

---

consul/base.py

I manually confirmed that it works for all the blocking endpoints.  I also adjusted the existing wait param comment to match Consul's docs (5m is the default wait timeout, not 10m), and duplicated it as necessary.

Support 'wait' param for all blocking queries

---

consul/base.py

Example:
```
File "/usr/local/lib/python2.7/dist-packages/blaze_cli-0.1-py2.7.egg/blazecli/commands/common.py", line 25, in consul_get_service
index, services = consul.catalog.service(servicename)
File "/usr/local/lib/python2.7/dist-packages/consul/base.py", line 1108, in service
'/v1/catalog/service/%s' % service, params=params)
File "/usr/local/lib/python2.7/dist-packages/consul/std.py", line 34, in get
self.session.get(uri, verify=self.verify)))
File "/usr/local/lib/python2.7/dist-packages/consul/base.py", line 119, in cb
data = json.loads(response.body)
File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
return _default_decoder.decode(s)
File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File …
```

Improve error when a HTTP 503 status code is returned

---

consul/base.py

The index system with events is different than the regular consul index system, check https://consul.io/docs/agent/http/event.html#event_list for more infos.
However, I don't see a reason to not support indexes here.

Added index and wait parameter to event.list

---

consul/base.py

Issue: #82 
This PR adds support for TCP and Docker health checks via HTTP API exposed by Consul v0.6.0.
Tests have not been updated as this requires update of consul binaries used in test. 0.5.2 -> 0.6.0 is a breaking update.

Add support for TCP and Docker health checks (v0.6.0)

---

consul/base.py

Other Hashicorp tools, envconsul and consul-template, use this set of environment variables to provide configuration for themselves and other consul tools they're integrated with.  I've implemented them as overrides to what is normally passed in to the constructor.  That seems to make sense since an application can be configured to use the default host/port but then be overridden by providing CONSUL_HTTP_ADDR.

Use standard consul environment variables to override configuration

---

.bumpversion.cfg
README.rst
consul/__init__.py

Proposing that the project use bumpversion to manage versions/release.
This also resolves #91.

Add bumpversion support

---

tests/conftest.py

This fix handles the case where multiple private interfaces exists on the developer machine. Currently, attempting to start the server will faile silently. This fix forces the use of the loopback interface.

tests: handle multiple private interfaces

---

consul/base.py

In a case where the acl_token is set to "anonymous" in consul server config, by default services in catalog are invisible, and trying to list them shows only "consul" service.
In context of #116

Catalog API should support tokens

---

consul/base.py

consul updates the session max TTL months ago, can we keep this up to date?
https://github.com/hashicorp/consul/pull/1412

fix #131: update max ttl to 86400 to conform to consul

---

consul/tornado.py
tests/test_std.py
tests/test_tornado.py

The `Consul.KV.put` docs state:
> _value_ can either be None (useful for marking a key as a
> directory) or any string type, including binary data (e.g. a
> msgpack'd data structure)
However, giving `None` as a value to the `consul.tornado` backend causes:
`ValueError: Body must not be None for method PUT (unless allow_nonstandard_methods is true)`
In this change the bug is corrected and tests are added, in three commits:
1. 2603ef3 exposes the error by copying the "encoding" tests from std to tornado.
2. 853e774 corrects the error by exploiting the existing treatment of empty string.
3. a4aee7c adds an additional test to std and tornado to explicitly show the treatment of empty string.

Tornado backend encoding bug

---

.travis.yml
consul/base.py
tests/conftest.py
tests/test_base.py

New in Consul 0.7.0 and higher, when the field `DeregisterCriticalServiceAfter` with a duration is added to a check, causes a service which is critical for longer than the interval to automatically be deregistered, including associated health check.
Includes tests for checks creating the appropriate fields.

Add support for DeregisterCriticalServiceAfter

---

consul/base.py

Currently it is not possible to fire an event, when events are restricted by ACL. This patch adds an option to set a token in Event.fire or if not set and a token is set for the agent, it uses the agent's token.

Add and use ACL token in Event.fire

---

setup.py

consul.aio is supported only in python3 and depends on aiohttp which
requires python>=3.4.2
Resolves: #123 #118

consul.aio: skip installation if python<3.4.2

---

consul/aio.py
consul/base.py
consul/std.py
consul/tornado.py
consul/twisted.py
tests/test_std.py

I have created a base abstract class for HttpClient implementations. As this allows us to enforce interfaces and also write common functionality (think uri method) once.
Based on the above work, I have also added a fix for #156 to quote uri and added a test case for the issue.

HttpClient base class and url quoting

---

tests/conftest.py

This PR improves separation of unittests by removing not only all keys from KV storage but also deregistering of all services. Moreover, multiple small improvements were introduced.

Unittest fix

---

consul/base.py
tests/test_base.py

I like to add meta data to my services, this allows just that. It's a variation of #222

Allow adding meta data when registering service
