cablehead/python-consul

consul/base.py, consul/std.py, consul/tornado.py
Here's my stab at closing #16.
=> Closes #16. Add ability to use SSL

consul/aio.py, tests/conftest.py, tests/test_aio.py, tox.ini
Hi,
I have added adapter for asyncio support using aiohttp as http client. All tests was ported from tornado, and couple of them still failing. Looks like I need to fix time sleep constants. 
Please review.
=> Add asyncio support

docs/index.rst
=> docs for asyncio adapter

consul/base.py, tests/test_std.py
I find it easier to use HTTP checks sometimes, as documented here (under HTTP+Interval):
http://www.consul.io/docs/agent/checks.html
I hope I sorted out the tests and assertions properly.
=> Add HTTP check support

.gitignore, consul/base.py, tests/test_std.py, tox.ini
Finally got back around to this. Added keys and separator parameters to the kv.get method, and added the event namespace (event.fire and event.list methods).
=> Added events interface, added support for kv.get keys and separator parameters

consul/base.py
=> Add `cas` option flag for kv.delete

consul/base.py
This should fix https://github.com/cablehead/python-consul/issues/36. I did a quick test and it worked fine. Thanks for taking a look!
=> Adding ability to register checks with services

consul/base.py, tests/test_std.py
=> Node and Service Maintenance

consul/aio.py, tests/test_aio.py
I've added ``__del__`` magic method in order to close http connections on garbage collection, like aiohttp/aiopg/aiomysql does. This PR address #47 issue too.
=> add finalizer to the __del__ magic method for python3.4.1

consul/base.py, tests/test_std.py
=> add health/node/<node> endpoint

consul/base.py, tests/test_std.py
Fixes #50 
Let me know if I'm missing anything. TM!
=> Issue 50 - Add status endpoint

consul/base.py
Re-opening with flake8 fix and doc strings updated.  See #58
=> Support 'dc' argument to health endpoints v2

consul/base.py, tests/test_std.py
=> Adding /v1/health/checks endpoint

consul/base.py
=> Add support for join and force-leave

consul/base.py
- introduce BadRequest exception
- raise BadRequest exception if consul server responds with 400
=> base: handle 400 responses

CHANGELOG.rst, consul/aio.py, consul/base.py, consul/std.py, consul/tornado.py, tests/test_std.py
This PR supercedes PR#102. This PR squashes original commits, adds extra documentation and refactors redundant code. Additionally fixed test case.
=> Add Query API Support

consul/base.py, tests/test_std.py
Added coordinate endpoint and near support on Catalog and Health Checks endpoints #79 
also removed all lambda in order to get exception message #77
=> Added coordinate endpoint and near support on Catalog and Health Checks

consul/twisted.py, setup.py, tests/conftest.py, tests/test_twisted.py, tox.ini
=> twisted: add initial support using treq

consul/base.py
Correct the error message on creating/updating ACLs
Consul supports both JSON and HCL encoded ACLs
=> Correct error message in ACL create/update

consul/base.py, tests/test_std.py
Following issue #121 
Need this option too.
=> Allow enable tag override

consul/base.py, consul/twisted.py
=> update base.py to support python2.6

consul/base.py, tests/test_std.py
The new Operator endpoint is really useful for getting details on the state of the raft configuration.
I didn't add the delete peer endpoint yet.
Also had to add Stats to the agent_self test.
=> Adds Operator endpoint.

.travis.yml, tox.ini
Quick copy + paste to add testing support to 3.5 and 3.6.
=> Update CI: Add py35 and py36 to tests.

consul/aio.py, consul/base.py, consul/std.py, consul/tornado.py, consul/twisted.py, tests/test_base.py
Added the ability to add client certs to the consul connection
=> added client side cert support

consul/base.py
Improve exception error message when invalid CONSUL_HTTP_ADDR value is
provided.
Resolves #149
=> base: improve error message when configuring host

consul/base.py, tests/test_base.py
This PR adds header parameter to http check classmethod.
=> added header parameter to http check

CHANGELOG.rst, consul/base.py, tests/test_aio.py, tests/test_std.py, tests/test_tornado.py, tests/test_twisted.py
=> Add initial support for Transaction endpoint

consul/base.py, tests/conftest.py, tests/test_aio.py, tests/test_std.py, tests/test_tornado.py, tests/test_twisted.py
This PR adds support of Consul v 1.0.0. This PR fixes the following issues and PRs: #179, #178, #174, #175, #176
=> Consul 1 0 0

consul/base.py, tests/test_base.py
=> Manage additional 4xx HTTP status code #186

.bumpversion.cfg, .gitignore, consul/__init__.py, consul/base.py, sonar-project.properties, tests/test_aio.py, tests/test_tornado.py, tests/test_twisted.py
This PR also bumps the Consul test binaries to 1.1.0 and updates test assertions for agent/services calls as that now returns an addition `Meta` field.
=> Consul 1.1.0 has removed the script argument for checks.

consul/base.py
A minor fixed which is the missing changes from #190
=> Fix parmas usage
